"""Traductions i18n pour le rapport PDF (fr/en).

Source unique pour toutes les chaînes affichées dans le PDF.
Évite les mélanges fr/en en centralisant et en forçant lang cohérent.
"""

# Clés : identifiants. Valeurs : dict fr / en.
_PDF_STRINGS: dict[str, dict[str, str]] = {
    "cover_url_label": {"fr": "URL scannée", "en": "Scanned URL"},
    "cover_date_label": {"fr": "Date", "en": "Date"},
    "report_title": {"fr": "Rapport de scan de posture sécurité", "en": "Security Posture Scan Report"},
    "subtitle": {
        "fr": "Analyse non intrusive — TLS, headers, cookies, exposition",
        "en": "Non-intrusive analysis — TLS, headers, cookies, exposure",
    },
    "page_title": {"fr": "Rapport de scan", "en": "Scan report"},
    "disclaimer": {
        "fr": "Ce rapport est généré par SecureOps. Usage autorisé uniquement sur des sites dont vous avez la permission.",
        "en": "This report is generated by SecureOps. Use only on sites you are authorized to scan.",
    },
    "sommaire": {"fr": "Sommaire", "en": "Table of contents"},
    "synthese": {"fr": "Synthèse du scan", "en": "Scan summary"},
    "annexes": {"fr": "Annexes", "en": "Appendix"},
    "score": {"fr": "Score", "en": "Score"},
    "tests_performed": {"fr": "Tests effectués", "en": "Tests performed"},
    "test": {"fr": "Test", "en": "Test"},
    "status": {"fr": "Statut", "en": "Status"},
    "status_ok": {"fr": "OK", "en": "OK"},
    "anomalies": {"fr": "anomalies", "en": "findings"},
    "anomalies_one": {"fr": "anomalie", "en": "finding"},
    "details": {"fr": "Détails", "en": "Details"},
    "anomalies_detected_summary": {"fr": "anomalies ont été détectées", "en": "findings were detected"},
    "anomaly_detected_summary": {"fr": "anomalie a été détectée", "en": "finding was detected"},
    "no_anomaly_detected": {"fr": "Aucune anomalie détectée.", "en": "No finding detected."},
    "summary": {"fr": "Résumé", "en": "Summary"},
    "other_tests_section": {"fr": "Autres tests effectués", "en": "Other tests performed"},
    "other_tests_intro": {
        "fr": "Tests effectués n'ayant détecté aucune anomalie.",
        "en": "Tests performed that detected no anomalies.",
    },
    "repartition": {"fr": "Répartition des tests effectués par catégorie", "en": "Breakdown of tests performed by category"},
    "category": {"fr": "Catégorie", "en": "Category"},
    "count": {"fr": "Nb", "en": "Count"},
    "nb_tests": {"fr": "Nombre de tests", "en": "Tests count"},
    "nb_anomalies": {"fr": "Nombre d'anomalies détectées", "en": "Findings count"},
    "anomalies_detected": {"fr": "anomalies détectées", "en": "findings detected"},
    "anomaly_detected": {"fr": "anomalie détectée", "en": "finding detected"},
    "evidence": {"fr": "Preuve", "en": "Evidence"},
    "detail": {"fr": "Détail", "en": "Detail"},
    "how_to_fix": {"fr": "Comment corriger", "en": "How to fix"},
    "learn_more": {"fr": "En savoir plus :", "en": "Learn more:"},
    "severity_critical": {"fr": "Critique", "en": "Critical"},
    "severity_high": {"fr": "Élevé", "en": "High"},
    "severity_medium": {"fr": "Moyen", "en": "Medium"},
    "severity_low": {"fr": "Faible", "en": "Low"},
    "severity_info": {"fr": "Info", "en": "Info"},
    "matrix_gravite": {"fr": "Gravité \\ Vraisemblance", "en": "Severity \\ Likelihood"},
    "gravite_mineure": {"fr": "Mineure", "en": "Minor"},
    "gravite_significative": {"fr": "Significative", "en": "Significant"},
    "gravite_importante": {"fr": "Importante", "en": "Major"},
    "gravite_majeure": {"fr": "Majeure", "en": "Critical"},
    "vraisemblance_tres_faible": {"fr": "Très faible", "en": "Very low"},
    "vraisemblance_faible": {"fr": "Faible", "en": "Low"},
    "vraisemblance_forte": {"fr": "Forte", "en": "High"},
    "vraisemblance_tres_forte": {"fr": "Très forte", "en": "Very high"},
}

# Mapping gravité/vraisemblance du catalogue risk_matrix vers clés i18n
_GRAVITE_KEYS = {
    "Mineure": "gravite_mineure",
    "Significative": "gravite_significative",
    "Importante": "gravite_importante",
    "Majeure": "gravite_majeure",
}
_VRAISEMBLANCE_KEYS = {
    "Très faible": "vraisemblance_tres_faible",
    "Faible": "vraisemblance_faible",
    "Forte": "vraisemblance_forte",
    "Très forte": "vraisemblance_tres_forte",
}


def translate_gravite(gravite: str, lang: str) -> str:
    """Traduit une gravité du catalogue (fr) vers la langue demandée."""
    key = _GRAVITE_KEYS.get(gravite)
    return t(key, lang) if key else gravite


def translate_vraisemblance(vraisemblance: str, lang: str) -> str:
    """Traduit une vraisemblance du catalogue (fr) vers la langue demandée."""
    key = _VRAISEMBLANCE_KEYS.get(vraisemblance)
    return t(key, lang) if key else vraisemblance


def _normalize_lang(lang: str) -> str:
    """Retourne 'en' ou 'fr' (défaut fr)."""
    return "en" if lang == "en" else "fr"


def t(key: str, lang: str) -> str:
    """Retourne la traduction pour la clé et la langue.

    Args:
        key: Clé de traduction (ex. "sommaire", "evidence").
        lang: Code langue ("fr" ou "en").

    Returns:
        str: Chaîne traduite, ou la clé si absente.
    """
    lang = _normalize_lang(lang)
    entry = _PDF_STRINGS.get(key, {})
    return entry.get(lang, entry.get("fr", key))


def get_all_for_lang(lang: str) -> dict[str, str]:
    """Retourne toutes les traductions pour une langue (pour usage batch)."""
    lang = _normalize_lang(lang)
    return {k: v.get(lang, v.get("fr", k)) for k, v in _PDF_STRINGS.items()}
