"""Point d'entrée de configuration (réexporte app.config + settings).

Pour compatibilité : tous les imports depuis app.config_loader restent valides.
Le chargement est découpé dans app.config/ par domaine.
"""

from common.config_base import create_simple_settings

from app.config import (
    ApisEtFormatsSettings,
    AsyncJobsSettings,
    BlacklistSettings,
    CacheSettings,
    CookiesSettings,
    CorsCrossOriginSettings,
    DirectoryListingConfig,
    ExposedFileConfig,
    ExternalServicesSettings,
    InformationDisclosureSettings,
    IntegritySettings,
    MethodesHttpEtRedirectionsSettings,
    MultiScanSettings,
    PathCheckConfig,
    ScanTimeoutsSettings,
    ScoringSettings,
    SecurityHeaderConfig,
    SsrfSettings,
    UrlValidationSettings,
    get_apis_et_formats_settings,
    get_async_jobs_settings,
    get_blacklist_settings,
    get_cache_settings,
    get_cookies_settings,
    get_cors_cross_origin_settings,
    get_directory_listing_max_body,
    get_directory_listing_partial_extensions,
    get_directory_listing_partial_min_links,
    get_directory_listing_sensitive_403_paths,
    get_directory_listing_settings,
    get_exposed_files_max_body,
    get_exposed_files_settings,
    get_exposed_files_severity_upgrade,
    get_external_services_settings,
    get_information_disclosure_max_body,
    get_information_disclosure_settings,
    get_integrity_settings,
    get_methodes_http_et_redirections_settings,
    get_multi_scan_settings,
    get_robots_txt_settings,
    get_scan_timeouts,
    get_scoring_settings,
    get_security_headers_settings,
    get_sitemap_fallback_paths,
    get_ssrf_settings,
    get_tech_fingerprinting_thresholds,
    get_url_validation_settings,
)

settings = create_simple_settings("scan-service", default_port=8012, caller_file=__file__)

__all__ = [
    "ApisEtFormatsSettings",
    "BlacklistSettings",
    "AsyncJobsSettings",
    "CacheSettings",
    "MultiScanSettings",
    "CorsCrossOriginSettings",
    "CookiesSettings",
    "DirectoryListingConfig",
    "ExternalServicesSettings",
    "ExposedFileConfig",
    "InformationDisclosureSettings",
    "IntegritySettings",
    "MethodesHttpEtRedirectionsSettings",
    "PathCheckConfig",
    "ScanTimeoutsSettings",
    "ScoringSettings",
    "SecurityHeaderConfig",
    "SsrfSettings",
    "UrlValidationSettings",
    "get_cache_settings",
    "get_async_jobs_settings",
    "get_multi_scan_settings",
    "get_apis_et_formats_settings",
    "get_cors_cross_origin_settings",
    "get_directory_listing_max_body",
    "get_directory_listing_partial_extensions",
    "get_directory_listing_partial_min_links",
    "get_directory_listing_settings",
    "get_directory_listing_sensitive_403_paths",
    "get_cookies_settings",
    "get_external_services_settings",
    "get_blacklist_settings",
    "get_exposed_files_max_body",
    "get_exposed_files_settings",
    "get_exposed_files_severity_upgrade",
    "get_information_disclosure_max_body",
    "get_information_disclosure_settings",
    "get_integrity_settings",
    "get_methodes_http_et_redirections_settings",
    "get_robots_txt_settings",
    "get_sitemap_fallback_paths",
    "get_tech_fingerprinting_thresholds",
    "get_scoring_settings",
    "get_scan_timeouts",
    "get_security_headers_settings",
    "get_ssrf_settings",
    "get_url_validation_settings",
    "settings",
]
