"""Service de génération de rapports PDF pour les scans de posture sécurité.

Génère un PDF avec en-tête, score, findings et une matrice gravité/vraisemblance
par finding (croix dans la cellule correspondante).
"""

import io
from datetime import datetime
from html import escape
from typing import Any

from weasyprint import HTML

from app.catalogue.risk_matrix import get_gravite, get_vraisemblance

# Couleurs de la matrice (docs/verifications)
_COLORS = [
    ["#22c55e", "#22c55e", "#facc15", "#facc15"],  # Mineure
    ["#22c55e", "#facc15", "#f97316", "#f97316"],  # Significative
    ["#facc15", "#f97316", "#ef4444", "#ef4444"],  # Importante
    ["#f97316", "#ef4444", "#ef4444", "#ef4444"],  # Majeure
]
_GRAVITES = ("Mineure", "Significative", "Importante", "Majeure")
_VRAISEMBLANCES = ("Très faible", "Faible", "Forte", "Très forte")


def _gravite_index(gravite: str) -> int:
    """Retourne l'index de ligne pour la gravité."""
    try:
        return _GRAVITES.index(gravite)
    except ValueError:
        return 1


def _vraisemblance_index(vraisemblance: str) -> int:
    """Retourne l'index de colonne pour la vraisemblance."""
    try:
        return _VRAISEMBLANCES.index(vraisemblance)
    except ValueError:
        return 2


def _render_matrix(gravite: str, vraisemblance: str) -> str:
    """Génère le HTML d'une matrice avec croix à la position (gravité, vraisemblance).

    Args:
        gravite: Ligne (Mineure, Significative, Importante, Majeure).
        vraisemblance: Colonne (Très faible, Faible, Forte, Très forte).

    Returns:
        str: Fragment HTML de la matrice.
    """
    row_idx = _gravite_index(gravite)
    col_idx = _vraisemblance_index(vraisemblance)

    rows = []
    # En-tête
    header_cells = "<th style='border:1px solid #333;padding:6px;font-weight:bold'>Gravité \\ Vraisemblance</th>" + "".join(
        f"<th style='border:1px solid #333;padding:6px;font-weight:bold'>{escape(v)}</th>" for v in _VRAISEMBLANCES
    )
    rows.append(f"<tr>{header_cells}</tr>")

    for i, grav in enumerate(_GRAVITES):
        cells = []
        for j in range(4):
            bg = _COLORS[i][j]
            cross = "✗" if (i == row_idx and j == col_idx) else ""
            style = f"border:1px solid #333;padding:8px;background-color:{bg};min-width:50px;text-align:center"
            cells.append(f"<td style='{style}'>{escape(cross)}</td>")
        row_label = f"<td style='border:1px solid #333;padding:6px;font-weight:bold'>{escape(grav)}</td>"
        rows.append(f"<tr>{row_label}{''.join(cells)}</tr>")

    return f"<table style='border-collapse:collapse;margin:12px 0'>{''.join(rows)}</table>"


def _build_html(
    url: str,
    score: int | None,
    timestamp: str,
    duration: float,
    findings: list[dict[str, Any]],
    include_matrices: bool = True,
    lang: str = "fr",
) -> str:
    """Construit le HTML complet du rapport.

    Args:
        url: URL scannée.
        score: Score /100.
        timestamp: Horodatage ISO.
        duration: Durée en secondes.
        findings: Liste des findings (id, category, title, severity, evidence, recommendation, references).
        include_matrices: Inclure les matrices par finding.
        lang: Code langue (fr/en).

    Returns:
        str: Document HTML complet.
    """
    title = "Rapport de scan" if lang == "fr" else "Scan report"
    score_label = "Score" if lang == "fr" else "Score"
    url_label = "URL scannée" if lang == "fr" else "Scanned URL"
    date_label = "Date" if lang == "fr" else "Date"
    duration_label = "Durée (s)" if lang == "fr" else "Duration (s)"
    findings_label = "Findings" if lang == "fr" else "Findings"
    severity_label = "Sévérité" if lang == "fr" else "Severity"
    evidence_label = "Preuve" if lang == "fr" else "Evidence"
    recommendation_label = "Recommandation" if lang == "fr" else "Recommendation"
    disclaimer = (
        "Ce rapport est généré par SecureOps. Usage autorisé uniquement sur des sites dont vous avez la permission."
        if lang == "fr"
        else "This report is generated by SecureOps. Use only on sites you are authorized to scan."
    )

    try:
        dt = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
        date_str = dt.strftime("%d/%m/%Y %H:%M") if lang == "fr" else dt.strftime("%Y-%m-%d %H:%M")
    except (ValueError, TypeError):
        date_str = timestamp

    badge = "🟢" if (score or 0) >= 70 else "🟡" if (score or 0) >= 40 else "🔴"

    findings_html = []
    for f in findings:
        slug = f.get("id", "")
        title_f = escape(str(f.get("title", "")))
        severity = escape(str(f.get("severity", "")))
        evidence = escape(str(f.get("evidence", ""))[:500])
        recommendation = escape(str(f.get("recommendation", ""))[:500])

        block = f"""
        <div style='margin:16px 0;padding:12px;border:1px solid #ddd;border-radius:6px'>
            <h3 style='margin:0 0 8px 0;font-size:14px'>{title_f}</h3>
            <p style='margin:4px 0'><strong>{severity_label}:</strong> {severity}</p>
            <p style='margin:4px 0'><strong>{evidence_label}:</strong> {evidence}</p>
            <p style='margin:4px 0'><strong>{recommendation_label}:</strong> {recommendation}</p>
        """
        if include_matrices and slug:
            gravite = get_gravite(slug)
            vraisemblance = get_vraisemblance(slug)
            block += _render_matrix(gravite, vraisemblance)
        block += "</div>"
        findings_html.append(block)

    findings_section = (
        "".join(findings_html) if findings_html else ("<p>Aucun finding détecté.</p>" if lang == "fr" else "<p>No findings detected.</p>")
    )

    return f"""
<!DOCTYPE html>
<html lang="{lang}">
<head>
    <meta charset="UTF-8">
    <title>{title} - SecureOps</title>
    <style>
        body {{ font-family: system-ui, sans-serif; margin: 24px; color: #333; }}
        h1 {{ font-size: 20px; margin-bottom: 8px; }}
        .header {{ margin-bottom: 24px; }}
        .score {{ font-size: 28px; margin: 8px 0; }}
        .meta {{ font-size: 12px; color: #666; }}
        footer {{ margin-top: 32px; font-size: 10px; color: #888; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>SecureOps — {title}</h1>
        <p class="meta">{url_label}: {escape(url)}</p>
        <p class="meta">{date_label}: {date_str} | {duration_label}: {duration:.1f}</p>
        <p class="score">{score_label}: {score or 0}/100 {badge}</p>
    </div>
    <h2 style="font-size:16px">{findings_label}</h2>
    {findings_section}
    <footer>
        <p>{disclaimer}</p>
        <p>https://secureops.example.com</p>
    </footer>
</body>
</html>
"""


def generate_pdf(
    url: str,
    score: int | None,
    timestamp: str,
    duration: float,
    findings: list[dict[str, Any]],
    include_matrices: bool = True,
    lang: str = "fr",
) -> bytes:
    """Génère le PDF du rapport de scan.

    Args:
        url: URL scannée.
        score: Score /100.
        timestamp: Horodatage ISO.
        duration: Durée en secondes.
        findings: Liste des findings.
        include_matrices: Inclure les matrices gravité/vraisemblance par finding.
        lang: Code langue (fr/en).

    Returns:
        bytes: Contenu binaire du PDF.
    """
    html_content = _build_html(
        url=url,
        score=score,
        timestamp=timestamp,
        duration=duration,
        findings=findings,
        include_matrices=include_matrices,
        lang=lang,
    )
    buffer = io.BytesIO()
    HTML(string=html_content).write_pdf(buffer)
    return buffer.getvalue()
